apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
spec:
  ports:
  - port: 80
    targetPort: hello-world-port
  selector:
    app: hello-world
  type: LoadBalancer