apiVersion : apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: test
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      serviceAccountName: hello-world
      containers:
      - name: hello-world 
        image: senzakstest.azurecr.io/zachtest:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: secret1
            valueFrom:
              configMapKeyRef:
                name: config
                key: secret1
