apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: zachtest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zachtest 
    spec:
      containers:
        - name: zachtest 
          image: senzakstest.azurecr.io/zachtest
          ports:
          - containerPort: 80