apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: zachtest 
          image: senzakstest.azurecr.io/zachtest:latest
          ports:
          - containerPort: 3000
          - name: hello-world-port