apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
  selector:
    app: hello-world

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world
  labels:
    account: hello-world