apiVersion: v1
kind: Service
metadata:
    name: hello-world-service
spec:
    type: LoadBalancer
    ports:
    - port: 80 
        targetPort: hello-world-port
    selector:
        app: hello-world