apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
type: Opaque
data:
  # username: grafana
  username: Z3JhZmFuYQ0K
  # passphrase: Unsw85474?
  passphrase: VW5zdzg1NDc0Pw0K