apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  # username: kiali
  username: a2lhbGkNCg==
  # passphrase is Unsw85474?
  passphrase: VW5zdzg1NDc0Pw0K